name: deex
description: A state management library for Flutter, inspired by GetX, focusing exclusively on state management.
version: 0.0.1+2
homepage: https://github.com/rkpontes/deex

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.4.0 <0.6.0"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
